language: go
go: 1.9
services:
- docker

script:
  - make krew-index
  - make builddocker
  - if [ -n "$TRAVIS_TAG" ]; then TAG=$TRAVIS_TAG make releases; fi 

deploy:
  - provider: releases
    prerelease: true
    api_key: ${GITHUB_TOKEN}
    file:
      - rbac-view.${TRAVIS_TAG}.linux.tar.gz
      - rbac-view.${TRAVIS_TAG}.windows.tar.gz
      - rbac-view.${TRAVIS_TAG}.darwin.tar.gz
    skip_cleanup: true
    on:
      tags: true
